name: Build
on: push
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install zip
        run: sudo apt-get install -y jq
      - id: getname
        run: |
          echo "NAME=$(cat info.json | jq '.id' | tr -d '"')" >> "$GITHUB_ENV"
          echo "ICON=$(cat info.json | jq '.icon' | tr -d '"')" >> "$GITHUB_ENV"
      - name: Download Database
        run: wget https://github.com/skywind3000/ECDICT/releases/download/1.0.28/ecdict-sqlite-28.zip
      - name: extract-7z-action
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ecdict-sqlite-28.zip
          pathTarget: Database
      - uses: vimtor/action-zip@v1
        with:
          files: info.json ${{ env.ICON }} main.js Database
          dest: ${{ env.NAME }}.potext
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }}.potext
          path: "*.potext"
          if-no-files-found: error
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "*.potext"
